spring:
  datasource:
    url: jdbc:mysql://localhost/lunchtagauth?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual-creation: true
server:
  port: 9999