spring:
  datasource:
    url: ec2-54-247-169-129.eu-west-1.compute.amazonaws.com
    username: d9akbcdn2thqmd
    password: czichhctzfpnca
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual-creation: true
server:
  port: 9999